apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "nyoba-echo"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rudirahmat07/nyoba2.git
    targetRevision: main
    path:
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m