apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "nyoba-terus"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rudirahmat07/Nyoba2.git
    targetRevision: main
    path: nyoba-echo
  destination:
    server: https://kubernetes.default.svc
    namespace: rudi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m